# POST http://localhost:3000/cafes
# Content-Type: application/json

# { 
#   "name":"stabies", 
#   "description": "starbies1", 
#   "location":"prime"
# }

# POST http://localhost:3000/employees
# Content-Type: application/json

# { 
#   "name": "name", 
#   "emailAddress": "emailAddress@gmail.com", 
#   "phoneNumber": "99999999", 
#   "gender": "male",
#   "cafeId": "06d2d2bb-60ff-4404-bd0b-b4b22147b9b4"
#   }

# DELETE http://localhost:3000/employees
# Content-Type: application/json

# { 
#   "employeeId": "UI0000021"
#   }